import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'oorsi-web-product-list',
    templateUrl: './product-list.component.html',
    styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {

    products;

    constructor() { }

    ngOnInit() {
        this.products = [{
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 5389000,
            "name": "Sony - PlayStation 4 Console Uncharted 4: A Thief's End Bundle",
            "active": true,
            "regularPrice": 299.99,
            "salePrice": 249.99,
            "onSale": true,
            "onlineAvailability": true,
            "shortDescription": "Journey through the gaming universe with nearly limitless possibilities",
            "longDescription": "Play online, enjoy single player and game on with this PlayStation 4 Uncharted bundle. It includes a matching DualShock wireless controller and Uncharted 4: A Thief's End so that you can instantly enjoy the latest title in this legendary series. Outstanding graphics and compatibility with Blu-ray ensures this PlayStation 4 Uncharted bundle is a complete entertainment package.",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/5389/5389000_sa.jpg",
            "largeFrontImage": "http://img.bbystatic.com/BestBuy_US/images/products/5389/5389000_sa.jpg",
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/5389/5389000fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5389/5389000_s.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/5389/5389000_sb.jpg",
            "manufacturer": "Sony",
            "frequentlyPurchasedWith": [],
            "relatedProducts": []
        },
        {
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 5388900,
            "name": "Sony - PlayStation 4 Pro Console",
            "active": true,
            "regularPrice": 399.99,
            "salePrice": 399.99,
            "onSale": false,
            "onlineAvailability": true,
            "shortDescription": "Journey through the gaming universe with nearly limitless possibilities",
            "longDescription": "PS4 Pro  Dynamic 4K Gaming & 4K Entertainment*  PS4 Pro gets you closer to your game. Heighten your experiences. Enrich your adventures. Let the super-charged PS4 Pro lead the way.**  GREATNESS AWAITS",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/5388/5388900_sa.jpg",
            "largeFrontImage": "http://img.bbystatic.com/BestBuy_US/images/products/5388/5388900_sa.jpg",
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/5388/5388900fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5388/5388900_s.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/5388/5388900_sb.jpg",
            "manufacturer": "Sony",
            "frequentlyPurchasedWith": [],
            "relatedProducts": []
        },
        {
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 4743301,
            "name": "Sony - BDP-S3700 - Streaming Wi-Fi Built-In Blu-ray Player - Black",
            "active": true,
            "regularPrice": 119.99,
            "salePrice": 119.99,
            "onSale": true,
            "onlineAvailability": true,
            "shortDescription": "Wi-FiStream mediaYouTubeDolby TrueHD and DTS-HDBlu-ray Disc, DVD, CD and more",
            "longDescription": "Enjoy fast, high-definition media streaming with this Sony Blu-ray disk player optimized with built-in Wi-Fi for smooth video performance. Use your mobile device to remotely control the player, and view the convenient side-bar app for program information. Brilliant color and high-quality details add to watching enjoyment with this Sony Blu-ray disk player.",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/4743/4743301_sa.jpg",
            "largeFrontImage": "http://img.bbystatic.com/BestBuy_US/images/products/4743/4743301_sa.jpg",
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/4743/4743301fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/4743/4743301_s.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/4743/4743301_sb.jpg",
            "manufacturer": "Sony",
            "frequentlyPurchasedWith": [],
            "relatedProducts": []
        },
        {
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 8618136,
            "name": "Sony - Extra Bass Wireless Over-the-Ear Headphones - Black",
            "active": true,
            "regularPrice": 199.99,
            "salePrice": 89.99,
            "onSale": true,
            "onlineAvailability": true,
            "shortDescription": "Electronic Bass Boost circuitry; 40mm drivers; neodymium magnets; Bluetooth interface with AAC and aptX support; passive mode; built-in microphone; rechargeable battery; one-touch listening technology",
            "longDescription": "Enjoy your music with these Sony Extra Bass MDRXB950BT/B headphones, which feature Electronic Bass Boost circuitry for deep low-end sound. Bluetooth technology with AAC and aptX support allows easy wireless pairing with compatible devices.",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618136_sa.jpg",
            "largeFrontImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618136_sa.jpg",
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618136fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618136_s.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618136_sb.jpg",
            "manufacturer": "Sony",
            "frequentlyPurchasedWith": [],
            "relatedProducts": [
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8874374,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 4026018,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 4026054,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1154405,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 2912464,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 6582193,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1154093,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 2912419,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 5836896,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 3774098,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8383472,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8560331,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1154126,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1154354,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 3774112,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 4219008,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 3427062,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1154318,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8383589,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                }
            ]
        },
        {
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 8618232,
            "name": "Sony - ZX Series On-Ear Headphones - Black",
            "active": true,
            "regularPrice": 19.99,
            "salePrice": 9.99,
            "onSale": true,
            "onlineAvailability": true,
            "shortDescription": "Acoustic Bass Booster technology; 30mm drivers; neodymium magnets; swivel design; tangle-free Y-type cord",
            "longDescription": "These Sony ZX Series MDRZX110/BLK headphones feature neodymium magnets and 30mm drivers for powerful, reinforced sound. Enjoy your favorite songs with lush bass response thanks to the Acoustic Bass Booster technology.",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618232_sa.jpg",
            "largeFrontImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618232_sa.jpg",
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618232fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618232_s.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/8618/8618232_sb.jpg",
            "manufacturer": "Sony",
            "frequentlyPurchasedWith": [],
            "relatedProducts": [
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8618364,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8618214,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8618223,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8618205,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8618145,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8794539,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9636974,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9432866,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9470228,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9518182,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9470131,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 2132048,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9470177,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9470159,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9470219,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9470246,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9470273,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1433244,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1433445,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                }
            ]
        },
        {
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 5580915,
            "name": "Sony - DualShock 4 Wireless Controller for PlayStation 4 - Jet black",
            "active": true,
            "regularPrice": 59.99,
            "salePrice": 49.99,
            "onSale": true,
            "onlineAvailability": true,
            "shortDescription": "Built-in speaker; headset port; vibration; capacitive touch pad; click mechanism; extension port; SIXAXIS motion technology; light bar; three-axis gyroscope; three-axis accelerometer; built-in USB charging port; Bluetooth wireless technology; USB connectivity",
            "longDescription": "Play your favorite video games with this PlayStation 4 DualShock controller. The microUSB port lets you keep it charged and ready to use, and the trigger buttons and controls deliver immediate response on even the most challenging games. This PlayStation 4 DualShock controller has an internal speaker for realistic close-up sound.",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/5580/5580915_sa.jpg",
            "largeFrontImage": "http://img.bbystatic.com/BestBuy_US/images/products/5580/5580915_sa.jpg",
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/5580/5580915fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5580/5580915_s.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/5580/5580915_sb.jpg",
            "manufacturer": "Sony",
            "frequentlyPurchasedWith": [],
            "relatedProducts": []
        },
        {
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 8945804,
            "name": "Sony - $20 PlayStation Network Card",
            "active": true,
            "regularPrice": 20,
            "salePrice": 20,
            "onSale": false,
            "onlineAvailability": true,
            "shortDescription": "Enhance your enjoyment of your PlayStation system",
            "longDescription": "Broaden the content you enjoy on your PlayStation system with this convenient $20 PlayStation Network Card. Use the card to purchase downloadable games, game add-ons, full-length movies, TV shows and other content that you can play or view on your PlayStation 4, PlayStation 3 or PS Vita.",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/8945/8945804_sa.jpg",
            "largeFrontImage": "http://img.bbystatic.com/BestBuy_US/images/products/8945/8945804_sa.jpg",
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/8945/8945804fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8945/8945804_s.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/8945/8945804_sb.jpg",
            "manufacturer": "Sony",
            "frequentlyPurchasedWith": [
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1252962,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9394265,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8945779,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1253176,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 3592032,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1272814,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1284206,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 2103577,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1752066,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 3839439,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                }
            ],
            "relatedProducts": [
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1299006,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9394265,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8440046,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1504345,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 9928881,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8945779,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1299015,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 8438015,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                },
                {
                    "productId": null,
                    "retailer": "BEST_BUY",
                    "sku": 1297424,
                    "name": null,
                    "active": false,
                    "regularPrice": null,
                    "salePrice": null,
                    "onSale": false,
                    "onlineAvailability": false,
                    "shortDescription": null,
                    "longDescription": null,
                    "image": null,
                    "largeFrontImage": null,
                    "mediumImage": null,
                    "thumbnailImage": null,
                    "largeImage": null,
                    "manufacturer": null,
                    "frequentlyPurchasedWith": null,
                    "relatedProducts": null
                }
            ]
        },
        {
            "productId": null,
            "retailer": "BEST_BUY",
            "sku": 5286504,
            "name": "Zeiss - VR One Plus Virtual Reality Headset",
            "active": true,
            "regularPrice": 129.99,
            "salePrice": 99.99,
            "onSale": true,
            "onlineAvailability": true,
            "shortDescription": "Supports smartphones with screen sizes between 4.7 and 5.5 inch; no lens adjustment necessary; lightweight design; transparent front shield; detachable head strap and the over-the-head strap",
            "longDescription": "Immerse yourself into whole new worlds using your smartphone and this Zeiss VR One Plus Virtual Reality Headset. An easy-to-use tray holds your phone at the proper angle for 3-D viewing, and the device is compatible with a variety of smartphones and VR apps. This lightweight Zeiss VR One Plus Virtual Reality Headset is easy to wear for comfortable entertainment.",
            "image": "http://img.bbystatic.com/BestBuy_US/images/products/5286/5286504_rc.jpg",
            "largeFrontImage": null,
            "mediumImage": "http://img.bbystatic.com/BestBuy_US/images/products/5286/5286504fp.gif",
            "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5286/5286504_r.gif",
            "largeImage": "http://img.bbystatic.com/BestBuy_US/images/products/5286/5286504_rb.jpg",
            "manufacturer": "Zeiss",
            "frequentlyPurchasedWith": [],
            "relatedProducts": []
        }]

    }

}
